# Generated by Django 5.0.6 on 2024-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('miniatura', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
