# Generated by Django 5.0.6 on 2024-07-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='video',
            name='miniatura',
        ),
    ]
